### Numpy Mastery Assignment
- Answer all questions
- Submission : 20th September 2022

1. Create a 1D array of numbers from 0 to 9

In [133]:
import numpy as np
arr_1 = np.arange(0,10)
arr_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
type(arr_1)

numpy.ndarray

In [135]:
arr_1.ndim

1

2. Create a 3x3 numpy of all True 

In [136]:
all_true = np.full((3,3), True)
all_true

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

3. Create an array of numbers from 20 to 39

In [137]:
arr_2 = np.arange(20,40)
arr_2

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

4. Replace all odd numbers in Q3 by -1

In [138]:
arr_2[arr_2 % 2 != 0] = -1
arr_2

array([20, -1, 22, -1, 24, -1, 26, -1, 28, -1, 30, -1, 32, -1, 34, -1, 36,
       -1, 38, -1])

5. Create two arrays of length 10 and print out  common items in both arrays

In [11]:
arr_3 = np.arange(10,65,5)

arr_4 = np.arange(10,30,2)

np.intersect1d(arr_3,arr_4)

array([10, 20])

6.  Create a 5x5 identity matrix

In [139]:
arr_identity= np.eye(5)
arr_identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

7. In the code cell below define and print a set of arrays defined x, y and z. The array x should be take the form [10 12 9 2 20], y should have  101  values from  10  to  20  inclusive and z should be a  2×3  array of ones.

In [140]:
x = np.array([10,12,9,2,20])
x

array([10, 12,  9,  2, 20])

In [141]:
y = np.linspace(10,20,101)
y

array([10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9, 11. ,
       11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9, 12. , 12.1,
       12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8, 12.9, 13. , 13.1, 13.2,
       13.3, 13.4, 13.5, 13.6, 13.7, 13.8, 13.9, 14. , 14.1, 14.2, 14.3,
       14.4, 14.5, 14.6, 14.7, 14.8, 14.9, 15. , 15.1, 15.2, 15.3, 15.4,
       15.5, 15.6, 15.7, 15.8, 15.9, 16. , 16.1, 16.2, 16.3, 16.4, 16.5,
       16.6, 16.7, 16.8, 16.9, 17. , 17.1, 17.2, 17.3, 17.4, 17.5, 17.6,
       17.7, 17.8, 17.9, 18. , 18.1, 18.2, 18.3, 18.4, 18.5, 18.6, 18.7,
       18.8, 18.9, 19. , 19.1, 19.2, 19.3, 19.4, 19.5, 19.6, 19.7, 19.8,
       19.9, 20. ])

In [142]:
z = np.ones((2,3))
z

array([[1., 1., 1.],
       [1., 1., 1.]])

8.Using the available Numpy functions on array x from problem  7 , find the average and the standard deviation of the value in this array. Redefine x as an array with all these values sorted in numerical order.

In [143]:
x = np.array([10,12,9,2,20])
x

array([10, 12,  9,  2, 20])

In [144]:
average_x = np.mean(x)
average_x

10.6

In [145]:
std_dev_x = np.std(x)
std_dev_x

5.782732917920384

In [146]:
sort_x = np.sort(x)
sort_x 

array([ 2,  9, 10, 12, 20])

9. Create a 10x10 array with random values and find the minimum and maximum values

In [147]:
arr_5 = np.random.randint(100, size = (10,10))
arr_5

array([[ 3, 28, 33, 75, 82, 62, 67, 43, 52, 45],
       [66, 68, 34, 49, 48, 59, 71, 63, 58, 25],
       [53, 90, 61, 74, 21,  7, 21, 74, 39,  0],
       [57, 30, 84, 15, 74, 17, 37, 45,  3, 27],
       [23, 51, 85, 15, 90, 50, 45, 63, 62,  6],
       [86, 38, 25, 49, 15, 68, 36, 27, 73, 61],
       [36, 92,  1, 46, 41, 54, 13, 27, 18, 77],
       [64, 40, 60, 45, 78,  4, 99, 18, 30, 66],
       [32, 56, 66, 87, 68, 54, 77, 71, 42, 54],
       [26, 15, 24, 66, 36, 12, 55, 31, 56, 68]])

In [149]:
np.max(arr_5)

99

In [150]:
np.min(arr_5)

0

10. Create a 3x3 matrix with values ranging from 0 to 8

In [151]:
arr_6 = np.arange(0,9)
arr_6

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [152]:
np.reshape(arr_6,(3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

11.  Generates an array [[1 2 3] [4 5 6]]

In [153]:
arr_7 = np.array([[1,2,3],[4,5,6]])
arr_7

array([[1, 2, 3],
       [4, 5, 6]])

12. Generates an array [0 2.5 5 7.5 10]

In [154]:
arr_8 = np.array([[0,2.5,5,7.5,10]])
arr_8

array([[ 0. ,  2.5,  5. ,  7.5, 10. ]])

In [159]:
arr_ee = np.arange(0,11,2.5)
arr_ee

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

13. Generates an 3x3 array of zeros

In [160]:
arr_9 = np.zeros((3,3))
arr_9

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

14. Create array from 0.1 to 10 with 12 elements, inclusively

In [47]:
arr_10 = np.linspace(0.1,10,12)
arr_10

array([ 0.1,  1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1,
       10. ])

15. Create a matrix with seven columns and five rows of ten(10).

In [51]:
arr_11 = np.full((5,7),10)
arr_11

array([[10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10]])

16. What is the difference between numpy and list?

In [ ]:
""""
- NumPy is a Python library used for numerical computing, 
while a list is a built-in Python data structure that stores a collection of items.

- Also, a list can contain items of any data type, 
while NumPy arrays are homogeneous and can only contain items of the same data type. 

""""

17. Create a 1D array of ones consisting of  50  values. Change the values of the array so that the values alternate between ones and zeros ie  1,0,1,0,1,0,1,0,1...  ensuring that the starting value is  1 

In [61]:
ones_array = np.ones(50,)
ones_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [57]:
ones_array[1::2] = 0
ones_array


array([1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.])

18. Generate a  10×10  matrix of zeros.
Make this matrix an identity matrix

In [68]:
arr_12 = np.zeros((10, 10))
arr_12

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

19. Generate an array x to be a  10×10  array of zeros. Redefine its diagonal components (from left to right) to equal one

In [118]:
all_zero = np.zeros((10,10))
all_zero

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [120]:
np.fill_diagonal(all_zero, 1)
all_zero

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

20. What is the dot products of this two matrix [[1,2],[3,4]] and [[5,6],[7,8]]

In [95]:
i = np.array([[1,2],[3,4]])
a = np.array([[5,6],[7,8]])

In [97]:
np.dot(i,a)

array([[19, 22],
       [43, 50]])

21.  Multiply these two matrix [[1,2],[3,4]] and [[5,6],[7,8]]

In [75]:
arr_13 = np.array([[1,2],[3,4]])
arr_14 = np.array([[5,6],[7,8]])
product_arr = arr_13 * arr_14
product_arr

array([[ 5, 12],
       [21, 32]])

22. Multiply this matrix  [[1,2],[3,4]] by a  scalar value of 5

In [76]:
scalar = 5
arr_prod = np.array([[1,2],[3,4]])
scalar_prod = scalar * arr_prod
scalar_prod

array([[ 5, 10],
       [15, 20]])

23. A = [[1,2],[3,4]] and B = transpose of A. Calculate AxB

In [87]:
A = np.array([[1,2],[3,4]])
B = np.transpose(A)
C = A * B
C

array([[ 1,  6],
       [ 6, 16]])

In [88]:
type(A)

numpy.ndarray

24. A= [[1,2],[3,4]] and B =  [[5,6],[7,8]]. Is A x B = B x A ? Show working

In [129]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [130]:
X = A * B
X

array([[ 5, 12],
       [21, 32]])

In [131]:
Y = B * A
Y

array([[ 5, 12],
       [21, 32]])

In [132]:
A * B == B * A

array([[ True,  True],
       [ True,  True]])

25. Creates an array [[0 1 2] [3 4 5]]
- Let A = first row of the matrix
- B = second row of the matrix
- C = second column of the Matrix
- D = first row, third column of the matrix
- print A , B , C, D

In [98]:
an_array = np.array([[0,1,2],[3,4,5]])
an_array

array([[0, 1, 2],
       [3, 4, 5]])

In [99]:
A = an_array[0]
A

array([0, 1, 2])

In [105]:
B = an_array[1]
B

array([3, 4, 5])

In [106]:
C = an_array[:,1]
C

array([1, 4])

In [109]:
D = an_array[0][2]
D

2